# Tell travis we need a copy of docker running
language: generic
sudo: required
services:
  - docker

# Build image using Dockerfile.dev
before_install:
  - docker build -t anshulkumarchoudhary/docker-learning-react -f Dockerfile.dev .

# Tell travis how to run our test suite.
script: 
  - docker run -e CI=true anshulkumarchoudhary/docker-learning-react npm run test

# Tell travis how to deploy code to AWS
deploy:
  provider: elasticebeanstalk
  region: "us-east-2"
  app: "docker-learning-react"
  env: "DockerLearningReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-555253957993"
  bucket_path: "docker-learning-react"